version: '3.5'
volumes:
  data:
services:
  db:
    image: mysql:latest
    ports:
      - "3307:3306"
    volumes:
      - ./db-dump:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=adminS3cr3t
      - MYSQL_DATABASE=todolist