version: '3.5'

services:
  db:
    image: mysql:5.7
    volumes:
      - ./init.sql:/data/application/init.sql
    environment:
      MYSQL_DATABASE: 'todolist'
      MYSQL_ROOT_PASSWORD: 's3cr3t'
    ports:
      - "3307:3306"
    expose:
      - "3307"